Update index.html
htmlacademy-htmlcss/2512285-sedona-1 pull request #2
Opened 2024-04-25 21:17 UTC by Wyziq

header plus body

2024-05-08 13:31 UTC, Kartaviy-arteom requested changes

2024-05-08 13:31 UTC, Kartaviy-arteom commented on hotels.html
> +              <img class="breadcrumbs-home-image" src="#" alt="">
img тут не нужен https://up.htmlacademy.ru/htmlcss-individual/1/criteries#IMG-01

2024-05-08 13:31 UTC, Kartaviy-arteom commented on hotels.html
> +          <button class="button" type="submit">Применитьы</button>
в макете есть еще кнопка для сброса формы

2024-05-08 13:31 UTC, Kartaviy-arteom commented on hotels.html
> +
пропущено "найдено гостиниц"

2024-05-08 13:31 UTC, Kartaviy-arteom commented on hotels.html
> +        </a>
список

2024-05-08 13:31 UTC, Kartaviy-arteom commented on hotels.html
> +            <a class="product-5-star button" href="#"></a>
<div class="rating stars4">
       span class="rating-stars visually-hidden">Рейтинг отеля 4 звезды.</span>
</div>

2024-05-08 13:31 UTC, Kartaviy-arteom commented on index.html
> +      </section>
первая секция

2024-05-08 13:31 UTC, Kartaviy-arteom commented on index.html
> +          </li>
преимуществ 5 и поэтому в списке должно быть 5 пунктов

2024-06-06 06:23 UTC, Wyziq commented on hotels.html
> +              <img class="breadcrumbs-home-image" src="#" alt="">
поправил

2024-06-06 06:31 UTC, Wyziq commented on hotels.html
> +          <button class="button" type="submit">Применитьы</button>
добавил

2024-06-06 06:48 UTC, Wyziq commented on hotels.html
> +
добавил

2024-06-06 06:55 UTC, Wyziq commented on hotels.html
> +        </a>
скорректировал

2024-06-06 06:57 UTC, Wyziq commented on index.html
> +          </li>
поправил

2024-06-06 07:02 UTC, Wyziq commented on index.html
> +      </section>
поправил

2024-06-06 07:08 UTC, Wyziq commented on hotels.html
> +            <a class="product-5-star button" href="#"></a>
а что тут? нет комментария

2024-06-06 07:13 UTC, Wyziq reviewed
по всем комментария внес правки, кроме одного - по нему написал вопрос

2024-06-06 07:19 UTC, Wyziq commented on hotels.html
> +            <a class="product-5-star button" href="#"></a>
комментарий увидел, поправил (он почему-то в VSC не прогрузился, а в Github есть)

2024-06-06 07:20 UTC, Wyziq reviewed
по всем комментариям внес правки

2024-06-06 08:05 UTC, Kartaviy-arteom requested changes
В целом все хорошо, буквально пару моментов

2024-06-06 08:05 UTC, Kartaviy-arteom commented on hotels.html
> +          <button class="button" type="cancel">Сбросить</button>
type reset https://developer.mozilla.org/ru/docs/Web/HTML/Element/button

2024-06-06 08:05 UTC, Kartaviy-arteom commented on index.html
> +        <a class="button button-all" href="#">Посмотреть все</a>
не увидел этой ссылки в макете

2024-06-06 08:05 UTC, Kartaviy-arteom commented on index.html
> +          <span class="search-button-text">Поиск гостиницы в Седоне</span>
этот спан не нужен, можно просто в кнопку вложить текст

2024-06-06 08:05 UTC, Kartaviy-arteom commented on hotels.html
> +            <a class="product-1-star button" href="#"></a>
тут не нужны ссылки и необходимо проверить именования классов https://up.htmlacademy.ru/htmlcss-individual/1/criteries#PROJ-02

2024-06-06 08:05 UTC, Kartaviy-arteom commented on hotels.html
> +          <input class="field" placeholder="email@example.com" type="email" name="footer-subscribe-email" id="footer-subscribe-email" required>
тут ввсего одно поле и нет смысла отправлять пустую форму. у input есть атрибут required

2024-06-06 08:05 UTC, Kartaviy-arteom commented on hotels.html
> +        <img class="footer-logo-img" src="#" alt="HTML Academy">
это ссылка на сайт академии

2024-06-06 08:05 UTC, Kartaviy-arteom commented on hotels.html
> +      <section class="footer-logo">
нет большого смысла формировать здесь секцию ради одной ссылки

2024-06-12 19:52 UTC, Wyziq commented on hotels.html
> +          <button class="button" type="cancel">Сбросить</button>
поправил

2024-06-12 20:06 UTC, Wyziq commented on hotels.html
> +            <a class="product-1-star button" href="#"></a>
изменил на список

2024-06-13 07:15 UTC, Wyziq commented on hotels.html
> +      <section class="footer-logo">
объединил секцию Контакты и Лого

2024-06-13 07:31 UTC, Wyziq commented on hotels.html
> +        <img class="footer-logo-img" src="#" alt="HTML Academy">
сделал ссылку, позже в стилях присоединю декортаивное лого

2024-06-13 07:50 UTC, Wyziq commented on hotels.html
> +          <input class="field" placeholder="email@example.com" type="email" name="footer-subscribe-email" id="footer-subscribe-email" required>
поправил

2024-06-13 07:52 UTC, Wyziq commented on index.html
> +        <a class="button button-all" href="#">Посмотреть все</a>
удалил

2024-06-13 07:53 UTC, Wyziq commented on index.html
> +          <span class="search-button-text">Поиск гостиницы в Седоне</span>
поправил

2024-06-13 07:55 UTC, Wyziq reviewed
сделал корректировки по комменатриям

2024-06-16 11:46 UTC, merged